version: "3.8"

services:
  postgres:
    build:
      context: ../..
      dockerfile: .infra/database/Dockerfile
    container_name: package-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: package_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
